### ISSUE TITLE
Still works? 

### ISSUE THREAD

**Issue by ghost** [David-Carrasco/Scrapy-Idealista#7]
When I run the script it seems that idealista is unreachable and it always respond with a 403 Forbbiden.

It seems that the owners have changed something in the secutiry aspect....

**Comment by DanielRD92** [comment]
I tried it some minutes ago and the crawling part works. Here you will find the answer #3  , spolier: you must set the timeout in 20 secs, but I read some people get results with 4 seconds. Although I'm having some issues with the text encoding now.

**Comment by David-Carrasco** [comment]
@DanielRD92, @staskbieto  pull the repo and try again.

The text encoding is fixed too.

I've tested the crawler with a timeout of 10 seconds and it works. If it can be a lower value, please let me know since I haven't been able to download a complete url with just 4 seconds, proxies fail from time to time.

Enjoy!

**Comment by DanielRD92** [comment]
Now it works perfectly! Thank you.

**Comment by David-Carrasco** [comment]
Fixed
